versions:
  "3.6.3.1":
    folder: all
  "3.5.2":
    folder: all
  # keep 3.2.1 for libcoap, libgit2, lief
  "3.2.1":
    folder: all
  # final 2.28.x (old LTS) version
  "2.28.10":
    folder: all
  # keep 2.6.12 for cose-c
  "2.16.12":
    folder: all
